### ISSUE TITLE
No Report Page

### ISSUE THREAD

**Issue by Betacarotin** [humhub/humhub-modules-reportcontent#2]
I can report posts but as a Admin I cant see reported postings. There is no Report Page and no notification.

**Comment by mrluisiko99** [comment]
+1. I don't receive any notification neither.

**Comment by mrluisiko99** [comment]
#1

**Comment by timvango** [comment]
+1 Kinda useless like this...

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-reportcontent/commit/11324d28709a8a59be8f6390758bbf17bf444896
