### ISSUE TITLE
Reported Posts are displayed as blank line in Notifications

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub-modules-reportcontent#21]
If a user reports content, there is no notification to the admin anymore. It seems that the report is notified as a blank line in the Notifications list. No email to admin either.
There is no way to know if a report is made, apart from going to the report content admin screen.

**Comment by staxDB** [comment]
Just discovered the same issue
<img width="362" alt="bildschirmfoto 2017-08-16 um 10 02 04" src="https://user-images.githubusercontent.com/8705799/29353367-3a4fbdf6-826a-11e7-852e-aa6aaf60903c.png">

**Comment by Felli** [comment]
There is an issue with the notifications, a rework in on the to-do list.
